### ISSUE TITLE
Just Poking

### ISSUE THREAD

**Issue by shellscape** [elcobvg/svelte-material#1]
Hey there, I got curious about the project so I cloned and poked it. Doesn't look like the last commit is buildable. I'd wager the project is probably dead, but I figured I'd pop in and let you know real quick anyhow. Cheers

**Comment by elcobvg** [comment]
Yeah sorry, this project is dead. No time for it anymore. Pretty sure there must be other packages out there doing Material Design for Svelte. Good luck!
